---

# Version 2021.06.26.0
# A one-off playbook that prepares a free tier Oracle Cloud VM running Ubuntu 20.04
# The Ubuntu 20.04 minimal image does not include Python, and swap is not enabled.
# This playbook address both of those issues.

# Swap portion derived from SO: 24765930

- hosts: all
  gather_facts: false
  become: true

  vars:
    swap_file: /swapfile
    swap_file_size: 1G
    swappiness: 1

  pre_tasks:
    - name: Install Python
      raw: 'sudo apt update && sudo apt -y install python'

  tasks:
    - name: Check if swap file exists
      stat:
        path: "{{ swap_file }}"
      register: swap_file_check

    - name: Create swap file
      command: fallocate -l {{ swap_file_size }} {{ swap_file }}
      when: not swap_file_check.stat.exists

    - name: Change swap file permissions
      file: path="{{ swap_file }}"
            owner=root
            group=root
            mode=0600

    - name: Format swap file
      command: "mkswap {{ swap_file }}"
      when: not swap_file_check.stat.exists

    - name: Write swap entry in fstab
      mount: name=none
             src={{ swap_file }}
             fstype=swap
             opts=sw
             passno=0
             dump=0
             state=present

    - name: Turn on swap
      command: swapon -a
      when: not swap_file_check.stat.exists

    - name: Set swappiness
      sysctl:
        name: vm.swappiness
        value: "{{ swappiness }}"
